# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: rss.xml

# Content
excerpt_link: Seguir leyendo
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: janitux
google_plus:
fb_admins:
fb_app_id:
